"""Generate the RoundPanel CJK subset from Noto Sans CJK (SIL OFL 1.1)."""
import argparse,re,subprocess,shutil
from pathlib import Path

root=Path(__file__).resolve().parents[1]
def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--converter',type=Path,help='Optional path to lv_font_conv.js')
    p.add_argument('--extra',type=Path,help='Local UTF-8 text containing additional characters; do not commit personal filenames')
    args=p.parse_args()
    chars=set(chr(i) for i in range(32,127))
    chars.update('（）【】[]：，。·℃%+-|_…')
    for folder in ['Hardware_Test','LVGL_UI','LVGL_Driver']:
        for source in (root/'firmware/main'/folder).glob('*.c'):
            if source.name.startswith('font_'):continue
            for literal in re.findall(r'"(?:[^"\\]|\\.)*"',source.read_text(encoding='utf-8')):
                chars.update(c for c in literal if ord(c)>=32 and c!='\\')
    if args.extra:chars.update(c for c in args.extra.read_text(encoding='utf-8') if ord(c)>=32)
    font=root/'assets/fonts/NotoSansCJKsc-Regular.otf'
    output=root/'firmware/main/LVGL_UI/font_music_cjk.c'
    command=['node',str(args.converter)] if args.converter else [shutil.which('npx') or 'npx','--yes','lv_font_conv@1.5.3']
    subprocess.run(command+['--font',str(font),'--symbols',''.join(sorted(chars)),'--size','16','--bpp','4','--no-compress','--no-prefilter','--format','lvgl','--lv-font-name','font_music_cjk','-o',str(output)],check=True)
    text=output.read_text(encoding='utf-8')
    text=re.sub(r'(?m)^ \* Opts:.*$', ' * Generated by tools/gen_font.py; see assets/fonts/LICENSE.',text)
    # Converter comments may contain the build machine's absolute paths.
    text=text.replace(str(font),'assets/fonts/NotoSansCJKsc-Regular.otf').replace(str(output),'firmware/main/LVGL_UI/font_music_cjk.c')
    text='#define LV_LVGL_H_INCLUDE_SIMPLE\n/* RoundPanel CJK subset; derived from Noto Sans CJK, SIL OFL 1.1. */\n'+text
    text=text.replace('.fallback = NULL','.fallback = &lv_font_montserrat_16')
    output.write_text(text,encoding='utf-8')
    print('Generated',len(chars),'characters')

if __name__=='__main__':main()
